nombre = input ("ingrese el nombre: ")
print( nombre + ", buen dia." )
numero1 = int (input ("ingrese el primer numero: "))
numero2 = int (input ("ingrese el segundo numero: "))
print (numero1 * numero2)